// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5124.PowerUp.commands;
import edu.wpi.first.wpilibj.command.Command;

import javax.swing.text.html.HTMLDocument.HTMLReader.IsindexAction;

import org.usfirst.frc5124.PowerUp.Robot;

/**
 *
 */
public class IntakeSubCommand extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	
	public static char intakeKey;
	public static final char IN = 0x52;
	public static final char OUT = 0x3E;
	public static final char STOP = 0x02;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public IntakeSubCommand() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.intake);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	Robot.intake.initPIDRange();
    	intakeKey = STOP;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if(ActivateButtonCommand.isActive) {
    		if(intakeKey == STOP) {
    			Robot.intake.setIntakePower(0);
    		}
    		if(intakeKey == IN) {
    			Robot.intake.setIntakePower(-1);
    		}
    		if(intakeKey == OUT) {
    			Robot.intake.setIntakePower(1);
    		}
    		Robot.intake.setFoldingPIDSetpoint(Robot.oi.joy.getRawAxis(3));
    		Robot.intake.setFolderPower(Robot.intake.getFoldingPIDResult());
    	}
    	else {
    		Robot.intake.setIntakePower(0);
    		Robot.intake.setFolderPower(0);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
