// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5124.PowerUp.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5124.PowerUp.Robot;

/**
 *
 */
public class LiftSubCommand extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	
	public static char liftKey;
	public static final char UP = 0x11;
	public static final char DOWN = 0xAA;
	public static final char MIDDLE = 0xEE;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public LiftSubCommand() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lift);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	liftKey = DOWN;
    	while(!Robot.lift.getBottomLimitSwitch());
    	Robot.lift.zeroEncoder();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if(Robot.lift.getBottomLimitSwitch() && Robot.lift.getLiftEncoder() != 0) {
    		Robot.lift.zeroEncoder();
    	}
    	if(liftKey == DOWN) {
    		Robot.lift.setLiftPIDSetPoint(0);
    	}
    	if(liftKey == UP) {
    		Robot.lift.setLiftPIDSetPoint(0);
    	}
    	if(liftKey == MIDDLE) {
    		Robot.lift.setLiftPIDSetPoint(0);
    	}
    	
    	Robot.lift.setLiftSpeed(Robot.lift.getLiftPIDResult());
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
